USE db_stock_control;

INSERT INTO categorias (nombre, descripcion) VALUES
    ('Bebidas', 'Gaseosas, aguas y jugos'),
    ('Limpieza', 'Articulos de limpieza para el hogar'),
    ('Almacen', 'Productos secos y envasados'),
    ('Electronica', 'Accesorios y pequenos electronicos'),
    ('Herramientas', 'Ferreteria y herramientas manuales');

INSERT INTO productos (nombre, descripcion, id_categoria, precio, stock_actual, stock_minimo, fecha_alta) VALUES
    ('Gaseosa Cola 1.5L', 'Botella de 1.5 litros', 1, 1500.00, 45, 10, CURDATE()),
    ('Agua Mineral 500ml', 'Botella de 500 ml', 1, 700.00, 6, 15, CURDATE()),
    ('Jugo de Naranja 1L', 'Jugo exprimido', 1, 1300.00, 22, 8, CURDATE()),
    ('Cerveza Rubia 1L', 'Retornable', 1, 1800.00, 30, 12, CURDATE()),
    ('Lavandina 1L', 'Lavandina concentrada', 2, 900.00, 25, 8, CURDATE()),
    ('Detergente 750ml', 'Detergente concentrado para vajilla', 2, 1200.00, 4, 10, CURDATE()),
    ('Esponja x3', 'Esponjas multiuso', 2, 600.00, 40, 15, CURDATE()),
    ('Trapo de piso', 'Trapo de algodon', 2, 500.00, 3, 10, CURDATE()),
    ('Arroz 1kg', 'Paquete de arroz blanco', 3, 1100.00, 65, 20, CURDATE()),
    ('Fideos 500g', 'Fideos secos tipo tallarin', 3, 800.00, 14, 15, CURDATE()),
    ('Aceite de Girasol 900ml', 'Botella de aceite', 3, 2100.00, 18, 10, CURDATE()),
    ('Yerba 1kg', 'Yerba mate compuesta', 3, 3200.00, 50, 15, CURDATE()),
    ('Auricular Bluetooth', 'Auricular inalambrico', 4, 15000.00, 9, 5, CURDATE()),
    ('Cargador USB-C', 'Cargador rapido 20W', 4, 8000.00, 2, 6, CURDATE()),
    ('Power Bank 10000mAh', 'Bateria portatil', 4, 22000.00, 7, 4, CURDATE()),
    ('Destornillador Phillips', 'Punta N2', 5, 2500.00, 13, 6, CURDATE()),
    ('Cinta Metrica 5m', 'Cinta metalica', 5, 3000.00, 1, 5, CURDATE()),
    ('Martillo de Carpintero', 'Mango de madera', 5, 6500.00, 8, 3, CURDATE());

INSERT INTO movimientos (id_producto, tipo, cantidad, fecha, motivo, usuario) VALUES
    (1, 'ENTRADA', 60, DATE_SUB(NOW(), INTERVAL 175 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (1, 'SALIDA', 15, DATE_SUB(NOW(), INTERVAL 150 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (9, 'ENTRADA', 90, DATE_SUB(NOW(), INTERVAL 150 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (9, 'SALIDA', 25, DATE_SUB(NOW(), INTERVAL 120 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (5, 'ENTRADA', 30, DATE_SUB(NOW(), INTERVAL 120 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (13, 'ENTRADA', 12, DATE_SUB(NOW(), INTERVAL 100 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (13, 'SALIDA', 3, DATE_SUB(NOW(), INTERVAL 90 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (3, 'ENTRADA', 25, DATE_SUB(NOW(), INTERVAL 90 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (3, 'SALIDA', 3, DATE_SUB(NOW(), INTERVAL 80 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (12, 'ENTRADA', 55, DATE_SUB(NOW(), INTERVAL 75 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (12, 'SALIDA', 5, DATE_SUB(NOW(), INTERVAL 60 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (16, 'ENTRADA', 15, DATE_SUB(NOW(), INTERVAL 60 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (17, 'ENTRADA', 6, DATE_SUB(NOW(), INTERVAL 55 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (17, 'SALIDA', 5, DATE_SUB(NOW(), INTERVAL 45 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (4, 'ENTRADA', 35, DATE_SUB(NOW(), INTERVAL 45 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (4, 'SALIDA', 5, DATE_SUB(NOW(), INTERVAL 30 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (10, 'ENTRADA', 20, DATE_SUB(NOW(), INTERVAL 30 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (10, 'SALIDA', 6, DATE_SUB(NOW(), INTERVAL 20 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (2, 'ENTRADA', 20, DATE_SUB(NOW(), INTERVAL 20 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (2, 'SALIDA', 14, DATE_SUB(NOW(), INTERVAL 10 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (6, 'ENTRADA', 10, DATE_SUB(NOW(), INTERVAL 15 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (6, 'SALIDA', 6, DATE_SUB(NOW(), INTERVAL 5 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (8, 'ENTRADA', 8, DATE_SUB(NOW(), INTERVAL 12 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (8, 'SALIDA', 5, DATE_SUB(NOW(), INTERVAL 3 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (14, 'ENTRADA', 5, DATE_SUB(NOW(), INTERVAL 10 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (14, 'SALIDA', 3, DATE_SUB(NOW(), INTERVAL 2 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (18, 'ENTRADA', 10, DATE_SUB(NOW(), INTERVAL 8 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (18, 'SALIDA', 2, DATE_SUB(NOW(), INTERVAL 1 DAY), 'Venta mostrador', 'Kyara Pacheco'),
    (15, 'ENTRADA', 10, DATE_SUB(NOW(), INTERVAL 6 DAY), 'Compra a proveedor', 'Administrador del Sistema'),
    (15, 'SALIDA', 3, DATE_SUB(NOW(), INTERVAL 1 DAY), 'Venta mostrador', 'Kyara Pacheco');